const SET_TOKEN = 'SET_TOKEN';
const LOGIN_HISTORY = 'LOGIN_HISTORY';
const LOGIN_STATUS = 'LOGIN_STATUS';
const CHECK_IS_ADMIN = 'CHECK_IS_ADMIN';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const SET_CUSTOM = 'SET_CUSTOM';
const ADD_USER = 'ADD_USER';
const REMOVE_USER = 'REMOVE_USER';

export {
	SET_TOKEN,
	LOGIN_HISTORY,
	LOGIN_STATUS,
	CHECK_IS_ADMIN,
	LOGIN_FAILURE,
	SET_CUSTOM,
	ADD_USER,
	REMOVE_USER
}
