const SAVE_TOKEN = 'SAVE_TOKEN';
const LOGIN_HISTORY = 'LOGIN_HISTORY';
const LOGIN_STATUS = 'LOGIN_STATUS';
const CHECK_IS_ADMIN = 'CHECK_IS_ADMIN';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const SET_USER = 'SET_USER_NAME';
const ADD_USER = 'ADD_USER';
const REMOVE_USER = 'REMOVE_USER';

export {
	SAVE_TOKEN,
	LOGIN_HISTORY,
	LOGIN_STATUS,
	CHECK_IS_ADMIN,
	LOGIN_FAILURE,
	SET_USER,
	ADD_USER,
	REMOVE_USER
}
